In [15]:
#2.1思考题 1.一维数组访问
import numpy as np
subjects=np.array(['Maths','English','Python','Chinese','Art','Database','Physics'])
names=np.array(['王微','肖良英','方绮雯','刘旭阳','钱易铭'])
subjects[[1,2,4]]

array(['English', 'Python', 'Art'], dtype='<U8')

In [16]:
names[-3]

'方绮雯'

In [17]:
    names[2:]

array(['方绮雯', '刘旭阳', '钱易铭'], dtype='<U3')

In [18]:
subjects[2:4]

array(['Python', 'Chinese'], dtype='<U8')

In [19]:
subjects[(subjects=='Physics')|(subjects=='English')]

array(['English', 'Physics'], dtype='<U8')

In [25]:
#二维数组访问
scores=np.array([[70,85,77,90,82,84,89],[60,64,80,75,80,92,90],[90,93,88,87,86,90,91],[80,82,91,88,83,86,80],[88,72,78,90,91,73,80]])
scores[[1,4]]

array([[60, 64, 80, 75, 80, 92, 90],
       [88, 72, 78, 90, 91, 73, 80]])

In [21]:
scores[[2,4]][:,(subjects=='Maths')|(subjects=='Python')]

array([[90, 88],
       [88, 78]])

In [22]:
scores[:,(subjects=='Maths')|(subjects=='Art')]

array([[70, 82],
       [60, 80],
       [90, 86],
       [80, 83],
       [88, 91]])

In [29]:
scores[(names=='王微')|(names=='刘旭阳')][:,(subjects=='English')|(subjects=='Art')]

array([[85, 82],
       [82, 83]])

In [30]:
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])