In [10]:
#2.1思考题 1.一维数组访问
import numpy as np
subjects=np.array(['Maths','English','Python','Chinese','Art','Database','Physics'])
names=np.array(['王微','肖良英','方绮雯','刘旭阳','钱易铭'])
subjects[[1,2,4]]

array(['English', 'Python', 'Art'], dtype='<U8')

In [11]:
names[-3]

'方绮雯'

In [12]:
    names[2:]

array(['方绮雯', '刘旭阳', '钱易铭'], dtype='<U3')

In [13]:
subjects[2:4]

array(['Python', 'Chinese'], dtype='<U8')

In [14]:
subjects[(subjects=='Physics')|(subjects=='English')]

array(['English', 'Physics'], dtype='<U8')

In [15]:
#2.二维数组访问
scores=np.array([[70,85,77,90,82,84,89],[60,64,80,75,80,92,90],[90,93,88,87,86,90,91],[80,82,91,88,83,86,80],[88,72,78,90,91,73,80]])
scores[[1,4]]

array([[60, 64, 80, 75, 80, 92, 90],
       [88, 72, 78, 90, 91, 73, 80]])

In [16]:
scores[[2,4]][:,(subjects=='Maths')|(subjects=='Python')]

array([[90, 88],
       [88, 78]])

In [17]:
scores[:,(subjects=='Maths')|(subjects=='Art')]

array([[70, 82],
       [60, 80],
       [90, 86],
       [80, 83],
       [88, 91]])

In [18]:
scores[(names=='王微')|(names=='刘旭阳')][:,(subjects=='English')|(subjects=='Art')]

array([[85, 82],
       [82, 83]])

In [19]:
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
#2.2多维数组运算
scores+np.array([0,0,-3,0,0,0,0])

array([[70, 85, 74, 90, 82, 84, 89],
       [60, 64, 77, 75, 80, 92, 90],
       [90, 93, 85, 87, 86, 90, 91],
       [80, 82, 88, 88, 83, 86, 80],
       [88, 72, 75, 90, 91, 73, 80]])

In [21]:
scores.mean(axis=1)

array([82.42857143, 77.28571429, 89.28571429, 84.28571429, 81.71428571])

In [22]:
R=np.random.uniform(-1,1,size=(3,4))

In [23]:
R.sum()

2.7979863461282726

In [24]:
#2.3随机游走
steps=100
walk=np.random.randint(0,2,size=(2,steps))
walk=np.where(walk>0,1,-1)
position=walk.sum(axis=1)
distance=np.sqrt(position[0]**2+position[1]**2)
distance
#猜测平均距离=sqrt(步长)

15.620499351813308

In [25]:
#综合练习
#1.1
market=np.array(['大润发','沃尔玛','好德','农工商'])
fruit=np.array(['苹果','香蕉','橘子','芒果'])

In [26]:
#1.2
price=np.random.uniform(4,10,size=(4,4))#超市为行,水果为列

In [27]:
#1.3
price[market=='大润发',fruit=='苹果']+1


array([6.47612503])

In [28]:
price[market=='好德',fruit=='香蕉']+1

array([8.16814413])

In [29]:
#1,4
price-2

array([[3.47612503, 5.4960751 , 6.56199637, 5.78677342],
       [4.13549006, 4.89473728, 5.67425219, 5.9343043 ],
       [3.58225437, 5.16814413, 2.90752485, 6.98856784],
       [2.16425833, 4.97205347, 3.18316281, 5.2002137 ]])

In [30]:
#1.5
price[:,(fruit=='苹果')|(fruit=='芒果')].mean(axis=0)

array([5.33953195, 7.97746482])

In [31]:
market[price[:,fruit=='橘子'].argmax()]

'大润发'

In [32]:
#2.1
steps=10
wlk3=np.random.normal(0,1,size=(3,steps))

In [33]:
#2.2
pos3=wlk3.cumsum(axis=1)
pos3

array([[-0.1037485 , -0.54398356,  0.42252438,  2.29861636,  1.8328302 ,
         1.5912277 , -0.11110943, -0.68350796,  0.46910597,  1.44904397],
       [ 2.14603387,  0.45755252,  1.46611234,  1.45272526,  0.10779999,
        -0.82675338,  0.46553412,  0.73331031,  0.70340771, -0.8182148 ],
       [-0.01493608, -0.58480674, -1.43646722, -2.08893404, -3.11496607,
        -1.91843578, -2.51691432, -2.67807398, -2.01518177, -1.42891051]])

In [34]:
#2.3
d3=np.sqrt(pos3[0]**2+pos3[1]**2+pos3[2]**2)
np.set_printoptions(precision=2)
d3

array([2.15, 0.92, 2.1 , 3.43, 3.62, 2.63, 2.56, 2.86, 2.19, 2.19])

In [35]:
abs(pos3[2]).max()

3.114966073373864

In [36]:
d3.min()

0.9204734368086512